name = "Data Smoother"
packages = ["bokeh==3.2.2", "panel", "markdown-it-py", "numpy", "scipy", "sqlite3", "pandas"]
[[fetch]]
files = ['gen_nubase.py', 'iid.py', 'bokeh_show.py', 'nubase2020.txt', 'binding_energy.csv','ionic_data.db']
from = './'
