name = "LPP viewer"
packages = ["bokeh==3.2.2", "panel==1.3.8", "markdown-it-py", "numpy", "scipy", "sqlite3"]
[[fetch]]
files = ['gen_nubase.py', 'iid.py', 'bokeh_show.py', 'ionic_data.db']
from = './'
